# Linter Options
options:
  merge-default-rules: true
  formatter: stylish
  max-warnings: 2
# File Options
files:
  include: '**/*.scss'
  ignore:
    - 'node_modules/**/*.*'
# Rule Configuration
rules:
  quotes:
    - 2
    -
      style: double
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq
  no-extends: 2
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  clean-import-paths: 0
  no-color-hex: 0
  no-color-keywords: 0
  no-color-literals: 0
  class-name-format:
    - 1
    -
      convention: 'hyphenatedbem'
  indentation:
    - 2
    -
      size: 4
  property-sort-order:
    - 2
    -
      order: alphabetical
      ignore-custom-properties: true
  variable-for-property: 0
